#!/bin/bash
pip install tqdm
pip install imageio
pip install moviepy
pip install fbpca
pip uninstall -y pillow
CC="cc -mavx2"
pip install -U --force-reinstall pillow-simd
#bleeding edge
#pip install git+git://github.com/fchollet/keras.git --upgrade
CUDA_REPO_PKG="cuda-repo-ubuntu1604_8.0.61-1_amd64.deb"
wget http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64/cuda-repo-ubuntu1604_8.0.61-1_amd64.deb
sudo dpkg -i cuda-repo-ubuntu1604_8.0.61-1_amd64.deb
sudo rm /var/lib/dpkg/lock
sudo dpkg --configure -a
sudo dpkg --configure -a
sudo apt-get update
sudo apt-get -y install cuda
# install cuDNN v6.0
CUDNN_TAR_FILE="cudnn-8.0-linux-x64-v6.0.tgz"
wget http://developer.download.nvidia.com/compute/redist/cudnn/v6.0/cudnn-8.0-linux-x64-v6.0.tgz
tar -xzvf cudnn-8.0-linux-x64-v6.0.tgz
sudo cp -P cuda/include/cudnn.h /usr/local/cuda-8.0/include
sudo cp -P cuda/lib64/libcudnn* /usr/local/cuda-8.0/lib64/
sudo chmod a+r /usr/local/cuda-8.0/lib64/libcudnn*
