#!/bin/bash
export PATH=/usr/local/cuda-8.0/bin${PATH:+:${PATH}}
export LD_LIBRARY_PATH=/usr/local/cuda-8.0/lib64${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}
pip install keras==2.0.9
pip install theano==0.9.0
pip install tensorflow
pip install --ignore-installed --upgrade tensorflow-gpu
KERAS_BACKEND=tensorflow python -c "from keras import backend"
wget http://developer.download.nvidia.com/compute/redist/cudnn/v6.0/cudnn-8.0-linux-x64-v6.0.tgz
tar -xzvf cudnn-8.0-linux-x64-v6.0.tgz
sudo cp -P cuda/include/cudnn.h /usr/local/cuda-8.0/include
sudo cp -P cuda/lib64/libcudnn* /usr/local/cuda-8.0/lib64/
sudo chmod a+r /usr/local/cuda-8.0/lib64/libcudnn*
sudo mkdir /cat
sudo mount /dev/xvdf1 /cat
mv /home/ubuntu/.keras/keras.json /home/ubuntu/.keras/keras_bak.json
mv fish/keras.json /home/ubuntu/.keras/keras.json
cd /home/ubuntu/anaconda2/lib/python2.7/site-packages/keras/engine
rm topology.pyc
rm topology.py
cp /cat/home/ubuntu/iciar/src/topology.py topology.py
cd /cat/home/ubuntu/iciar/
jupyter notebook
