#!/bin/bash

sudo mkdir /cat
sudo mount /dev/xvdf1 /cat
sudo mkdir /cat2
sudo mount /dev/xvdg1 /cat2
sudo mkdir /cat3
sudo mount /dev/xvdh1 /cat3
sudo mkdir /cat4
sudo mount /dev/xvdi1 /cat4


pip install tqdm
pip install imageio
pip install moviepy
pip install fbpca

pip uninstall -y pillow
CC="cc -mavx2"
pip install -U --force-reinstall pillow-simd

#bleeding edge
#pip install git+git://github.com/fchollet/keras.git --upgrade


# install CUDA Toolkit v8.0
# instructions from https://developer.nvidia.com/cuda-downloads (linux -> x86_64 -> Ubuntu -> 16.04 -> deb (network))
CUDA_REPO_PKG="cuda-repo-ubuntu1604_8.0.61-1_amd64.deb"
wget http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64/${CUDA_REPO_PKG}
sudo dpkg -i ${CUDA_REPO_PKG}
sudo apt-get update
sudo apt-get -y install cuda

# install cuDNN v6.0
CUDNN_TAR_FILE="cudnn-8.0-linux-x64-v6.0.tgz"
wget http://developer.download.nvidia.com/compute/redist/cudnn/v6.0/${CUDNN_TAR_FILE}
tar -xzvf ${CUDNN_TAR_FILE}
sudo cp -P cuda/include/cudnn.h /usr/local/cuda-8.0/include
sudo cp -P cuda/lib64/libcudnn* /usr/local/cuda-8.0/lib64/
sudo chmod a+r /usr/local/cuda-8.0/lib64/libcudnn*

conda install theano 

# set environment variables
export PATH=/usr/local/cuda-8.0/bin${PATH:+:${PATH}}
export LD_LIBRARY_PATH=/usr/local/cuda-8.0/lib64${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}

pip install tensorflow

cd /cat/home/ubuntu/cat
pip install keras==2.0.8

KERAS_BACKEND=tensorflow python -c "from keras import backend"

jupyter notebook
